title: ENGL 4771    
description: Social Media and Contemporary Literature. Cornell University, Spring 2025. Lindsay Thomas.
theme: just-the-docs

url: https://lindsaythomas.net/engl4771s25

aux_links:
  Course Canvas Site: https://canvas.cornell.edu/courses/73839
